# -*- coding: utf-8 -*-
"""On-Prem_Ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Re80bYG8zhK0hofqzs0TcrqTx_tJqcOt
"""

from google.colab import files
uploaded = files.upload()

pip install azure-storage-blob

from azure.storage.blob import BlobServiceClient
import os

# Azure Blob Storage connection string
connection_string = "DefaultEndpointsProtocol=https;AccountName=adfprojec;AccountKey=BQXCsL8QojYGMBFMb2C6j/AsI96auuDFHT0j1BAPzroPbk+HyxUtsFSvl12BFYmpbw14ojvFpt3V+AStNy1Frw==;EndpointSuffix=core.windows.net"

# Container name - now bronze
container_name = "bronze"

# Initialize BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Create the container if it doesn't exist
container_client = blob_service_client.get_container_client(container_name)
if not container_client.exists():
    container_client.create_container()
    print(f"Container '{container_name}' created.")

# List of CSV files to upload
uploaded_files = [
    "DimAirline.csv",
    "DimFlight.csv",
    "DimPassenger.csv"
]

# Function to upload files
def upload_files_to_blob(files):
    for filename in files:
        local_file_path = os.path.join('/content', filename)  # Path in Colab
        blob_name = f"On-prem/{filename}" # Store inside 'sql' folder in bronze

        if not os.path.exists(local_file_path):
            print(f"⚠️ File not found: {local_file_path}")
            continue

        with open(local_file_path, "rb") as file:
            blob_client = container_client.get_blob_client(blob_name)
            blob_client.upload_blob(file, overwrite=True)
            print(f"✅ Uploaded {filename} to {container_name}/{blob_name}")

# Upload
upload_files_to_blob(uploaded_files)